### PR TITLE
fix(259): add bundle size analysis comment as a comment on each pull request

### PR DESCRIPTION
**Pull request by nocodeventure-nl**
## Description
Added a new GitHub Actions workflow to track and report bundle size changes on pull requests.

### Changes
- Added `bundle-size.yml` workflow that:
  - Builds both base and PR branches
  - Calculates total bundle size
  - Provides detailed breakdown of JS and CSS files
  - Comments size differences on PRs automatically

### Testing
- Tested locally using act
- Verified workflow syntax and job configuration

### Notes
- Workflow triggers on PRs targeting main branch
- Uses GitHub token for PR comment permissions
- Timeout set to 15 minutes for build process

### Related
Inspired by similar workflow in tscircuit/core, but optimized for Vite applications

/claim #259

### CODE REVIEW

**Comment by nocodeventure-nl** [comment]
@seveibar We switched to using job summaries for now, as they should work fine until GitHub adds a comment scope we can utilize.

Screenshot - 2024-11-22T225328 162

image

**Comment by seveibar** [comment]
@nocodeventure-nl i don't think anyone will look at the build summaries, we should try to find a solution. I'm told that having a PR invoke an action (via a workflow dispatch) gets around the issue

**Comment by seveibar** [comment]
Also just a note on your bundle summary, you should use something vite-specific, it's kind of useless as-is. We want to know what makes the vite bundle so big

**Comment by ShiboSoftwareDev** [comment]
@melmathari helo, I tried to do this but failed. I want to pass it to you to see how it should be done. Could you please after you complete it check my pr and see where I've gone wrong?

**Comment by melmathari** [comment]
> @melmathari helo, I tried to do this but failed. I want to pass it to you to see how it should be done. Could you please after you complete it check my pr and see where I've gone wrong?

@ShiboSoftwareDev What do you mean as to complete  what...?

**Comment by ShiboSoftwareDev** [comment]
@melmathari if you check my pr you can see I succeeded with posting a comment on the pr, but failed to generate the analysis. The issue and the bounty are still up and I would like you to have a go at it.

**Comment by melmathari** [comment]
> @melmathari if you check my pr you can see I succeeded with posting a comment on the pr, but failed to generate the analysis. The issue and the bounty are still up and I would like you to have a go at it.

I won't be able to on the short run but kindly have a look at the files I modified in my repo. https://github.com/tscircuit/snippets/pull/274/files

**Pull request closed without merging**
