### PR TITLE
Reduced size of search text

### PR DESCRIPTION
**Pull request by anas-sarkez**
/claim #79
#79

### CODE REVIEW

**Comment by seveibar** [comment]
@anas-sarkez screenshot?

**Comment by anas-sarkez** [comment]
> @anas-sarkez screenshot?

Screenshot 2024-11-10 at 7 57 06 PM

**Comment by anas-sarkez** [comment]
here if I reduced to 10px
Screenshot 2024-11-10 at 7 59 10 PM

**Comment by seveibar** [comment]
Can you create a playwright test that searches for something with results.

**Comment by seveibar** [comment]
I cant tell from your screenshot how results will appear because you have an empty state, a playeright test is the best way to provide visual confirmation so we should switch to those instead

**Comment by anas-sarkez** [comment]
I'm not sure what are you want to reduce? the text input or search results?

Screenshot 2024-11-10 at 8 15 06 PM
Screenshot 2024-11-10 at 8 16 43 PM

**Comment by seveibar** [comment]
@anas-sarkez can you create a playwright test for this? The issue isn't your code (yet), the issue is the relative size of the window, playwright tests ensure that the dimensions are known (they're better than screenshots)

It should be easy to make for this one! and will ensure future people don't break it

**Pull request closed without merging**
