### PR TITLE
fix #175: zoom effect for schematic view

### PR DESCRIPTION
**Pull request by RohittCodes**
https://github.com/user-attachments/assets/c012a2bb-ac1c-4c19-ae47-6438f509b956

/claim #175

fixes: #175

### CODE REVIEW

**Comment by RohittCodes** [comment]
Lemme know if it's okay, I forgot this point,
> I don't want to get a bunch of mouse math into this project unnecessarily

I can iterate over the solution and will try to add the same to `useMouseMatrixTransform` and respective functions if required. I've not replaced the `useMouseMatrixTransform`, but included a little math to it, which isn't that complex, so I guess it won't be a problem.

**Review by seveibar — CHANGES_REQUESTED** [review]
well done! Yes ideally this math is included in the `useMouseMatrixTransform` library- otherwise it's difficult for others to maintain who are less familiar with matrix math

Also, to get the checks to pass just run `bun format`.

Thanks really awesome work!

**Comment by RohittCodes** [comment]
okay sure!

**Comment by RohittCodes** [comment]
@seveibar won't this be ideal if I work on the particular package, where the function is implemented? or is it good to be merged?

I'm talking about this repo: [use-mouse-matrix-transform](https://github.com/seveibar/use-mouse-matrix-transform)

**Comment by seveibar** [comment]
Yea this is in part why I increased the bounty. First you have to reproduce the issue inside of `use-mouse-matrix-transform` (it has a way of creating examples if i remember correctly) then you have to fix the reproduction. The upside of doing this is nobody has to worry about this issue anymore because we use `use-mouse-matrix-transform` a lot

**Comment by seveibar** [comment]
I just verified that the issue seems to be present in that repo's example so you may not need to make a reproduction!

image

**Comment by Satvik1769** [comment]
Hi, I solved this issue in the use-mouse-matrix-transform by zooming the only required element to zoom instead of zooming every part of canvas. I hope this help please check out issue #3 of use-mouse-matrix-transform.

**Comment by RohittCodes** [comment]
i guess the issue isn't with the `use-mouse-matrix-transform` I've updated it without any matrix-math logic this time, it updates the containerBounds, and handles the interactions based on position and the dimensions.
```
  const updateContainerBounds = useCallback(() => {
    if (!containerRef.current) return
    const rect = containerRef.current.getBoundingClientRect()
    containerBoundsRef.current = {
      width: rect.width,
      x: rect.left,
      y: rect.top,
    }
    setContainerWidth(rect.width)
  }, [])
```

the issue which the example in the referenced repo was facing because of the `relative` property and due to the modification in dimensions using `transform.d`.
here's more about it: 
https://github.com/seveibar/use-mouse-matrix-transform/pull/4#issuecomment-2466589666

**Comment by seveibar** [comment]
@RohittCodes the code looks ok, but are all these changes necessary? Can you reduce it to the minimum set of things that fix the issue? If it's just adding `relative`, that's better than including unneeded changes

**Comment by seveibar** [comment]
confirmed fix on preview, waiting to see if code can be reduced

**Comment by RohittCodes** [comment]
yeah reduced it! it was just the `transformOrigin` property

**Comment by RohittCodes** [comment]
@seveibar you can review it. it was just the css property which we were missing most probably.

**Pull request merged**
