### PR TITLE
refactor: search text

### PR DESCRIPTION
**Pull request by RohittCodes**
playwright tests are facing errors with the initial xs and md devices since they're hidden. will be pushing them after feedbacks (if necessary)

playwright-test for lg-devices:
before: search spec ts-Search-Input-lg

after-fix: search spec ts-Search-Input-lg-1 (2)

/claim #79 
fixes: #79

### CODE REVIEW

**Review by seveibar — CHANGES_REQUESTED** [review]
i'm requiring playwright tests for this one

**Review by seveibar — APPROVED** [review]
looks good! but the snapshot is out of date

**Comment by RohittCodes** [comment]
@seveibar updated the snapshots!

**Comment by seveibar** [comment]
@RohittCodes sorry i wrote that comment super quickly and didn't explain, see how "snippets" is in the header? If you merge with main we no longer have "snippets" in the header

**Review by seveibar — APPROVED** [review]
going to give a pass on the snapshot issue for now because other snapshots have the same issue and it doesn't seem to impact the testing too dramatically

**Pull request merged**
