### PR TITLE
updated changes

### PR DESCRIPTION
**Pull request by PALLAVIKHEDLE**
New button hover changes updated.

### CODE REVIEW

**Comment by seveibar** [comment]
@PALLAVIKHEDLE can you fix the merge conflict?

**Review by seveibar — APPROVED** [review]
looks good after merge conflict fixed!

**Comment by PALLAVIKHEDLE** [comment]
Done

**Comment by seveibar** [comment]
@PALLAVIKHEDLE you're failing typecheck and formatcheck

**Comment by seveibar** [comment]
you can fix format errors with `bun format`

**Comment by PALLAVIKHEDLE** [comment]
Done!

**Pull request closed without merging**
