### PR TITLE
fix: error message

### LINKED ISSUE #427: Improve error message of the already imported jlcpcb part
The error message is coming from the https://github.com/tscircuit/easyeda-converter, we can modify there and some parts of the message here to convey better message for this case

Image

The error message needs to improve when that component is already imported

### PR DESCRIPTION
**Pull request by Anshgrover23**
/claim #427 
Fixes #427 

#### Related PR:
Fixes here also: https://github.com/tscircuit/easyeda-converter/pull/137

### Screenshots:
- Before
Screenshot from 2024-12-26 19-50-58
- After
Screenshot from 2024-12-26 19-49-59

### CODE REVIEW

**Comment by Anshgrover23** [comment]
@imrishabh18 done.

**Review by imrishabh18 — COMMENTED** [review]
Looking more into this, I think we don't need to change anything in the snippets. Cause this toast is not visible, as we already have the dailog box for the already imported snippet, and the error message changed in the easyeda will be propagated here.

cc: @seveibar

**Comment by Anshgrover23** [comment]
@imrishabh18 yes i also think so.

**Review by seveibar — CHANGES_REQUESTED** [review]
this is a server-side issue

**Pull request closed without merging**
