### PR TITLE
Implemented Fork on ViewSnippetHeader 

### LINKED ISSUE #112: Implement Fork Button
When you hit "Fork" it just opens the editor with the code from the snippet

### PR DESCRIPTION
**Pull request by ni9999**
### Fixes #112

### CODE REVIEW

**Review by seveibar — APPROVED** [review]
nice work!

**Comment by ni9999** [comment]
Thanks @seveibar . Btw understanding the codebase was a challenging task for me. Lots of components, hooks, routes.

**Comment by seveibar** [comment]
@ni9999 it can be quite tricky, glad you were able to figure it out. Do you see any areas where it could be improved?

**Comment by ni9999** [comment]
Not much. Also I have little idea as being relatively new in frontend. I thought about reducing hooks and components by defining some function of these directly in the components and pages. ie reducing the numbers of files. But it will decrease reusability.

Also make some documentation of snippet-api usage

**Pull request merged**
