### PR TITLE
Fixes Command palette search

### LINKED ISSUE #119: CmdK Menu Doesn't Search Snippets Properly (no results when searching)
I've reproduced this several times, the react-query setup is likely wrong, it needs to keep searching with a queryKey that is unique for the search string

Image

### PR DESCRIPTION
**Pull request by mrudulpatil18**
Fixes #119 

Changes:
- Rewrote a bunch of logic to fix the search filtering issue
- Now uses Fuzzy search to filter possible commands in the CMD-K menu
- This fixes the searching results not shown issue

cc: @seveibar

### CODE REVIEW

**Comment by mrudulpatil18** [comment]
NOTE: still requires a bit of work with a weird bud and some refactoring, will do when i get some free time

**Review by seveibar — APPROVED** [review]

**Review by seveibar — APPROVED** [review]
Sounds good! Yea i prefer the cmdk library so i support the change

**Comment by seveibar** [comment]
@mrudulpatil18 can we merge to capture these changes?

**Comment by mrudulpatil18** [comment]
> @mrudulpatil18 can we merge to capture these changes?

Yup, it's working as of now

**Comment by mrudulpatil18** [comment]
@seveibar 
added absolute position for the cmd-k dialog

**Pull request merged**
