### PR TITLE
split: footprint-dialog.spec.ts into multiple files

### LINKED ISSUE #364: Split `footprint-dialog.spec.ts` into multiple files
/bounty $10

Image

### PR DESCRIPTION
**Pull request by Anshgrover23**
Fixes #364 
/claim #364

### CODE REVIEW

**Review by seveibar — COMMENTED** [review]
can you put all of these into a folder "footprint-dialog" since they're all related to the footprint dialog

also CCing @ShiboSoftwareDev for review (his is more important)

**Comment by Anshgrover23** [comment]
@seveibar done.

**Comment by Anshgrover23** [comment]
the tests are failing here but locally it passes 
Screenshot from 2024-12-09 16-26-43

**Comment by ShiboSoftwareDev** [comment]
looks good to me, make sure the tests are passing

**Comment by Anshgrover23** [comment]
@ShiboSoftwareDev @seveibar ✅💎

**Review by ShiboSoftwareDev — APPROVED** [review]

**Pull request merged**
