### PR TITLE
fix: Regex to support underscore as well

### LINKED ISSUE #313: Cmd Click is broken for clicking on snippets
There is no underline and you can't click on it

Image

### PR DESCRIPTION
**Pull request by Anshgrover23**
Fixes #313 
/claim #313 

Screenshot from 2024-12-05 17-34-42

### CODE REVIEW

**Comment by Anshgrover23** [comment]
https://github.com/user-attachments/assets/9b2e8beb-f4de-4d57-9e5d-016294abbc80

**Review by seveibar — APPROVED** [review]
/tip $5

**Comment by Anshgrover23** [comment]
@seveibar is the tip delayed, or any problem on algora side, because i did not get that yet.

**Comment by Anshgrover23** [comment]
@seveibar i think the tip did not get transferred to me.

**Comment by seveibar** [comment]
@Anshgrover23 probably because there wasnt a bounty on the issue being solved, sorry

**Comment by seveibar** [comment]
Yep sorry. I dont debug payments, take it up with algora. If it doesnt go through it wasnt meant to be

**Pull request merged**
